-- Raw table to land initial data
CREATE OR REPLACE TABLE DEMO_RAW (
    ID NUMBER,
    NAME STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Simple analytics table
CREATE OR REPLACE TABLE DEMO_ANALYTICS (
    ID NUMBER,
    NAME_UPPER STRING,
    LOAD_TS TIMESTAMP_NTZ
);
